stages:
  - build
  - test
  - deploy

# Define a shared configuration using YAML anchors
.default-docker-jobs: &default-docker-jobs
  tags:
    - macos
  image: docker:20.10.24
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""  # Disable TLS for Docker-in-Docker
  before_script:
    - echo "Installing Docker Compose in Alpine Linux-based container"
    - apk add --no-cache docker-compose
  after_script:
    - docker-compose down -v

build:
  stage: build
  tags:
    - macos
  <<: *default-docker-jobs
  script:
    - docker info
    - docker-compose version
    - echo "Building Docker images..."
    - docker-compose build

test:
  stage: test
  tags:
    - macos
  script:
    - echo "Running tests for Python service1..."
    - pytest service1/test/service.py


deploy:
  stage: deploy
  tags:
    - macos
  <<: *default-docker-jobs
  script:
    - echo "Cleaning up Docker containers..."
    - docker-compose down -v
    - echo "Deploying Docker containers..."
    - docker-compose up --build -d
