version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8198:8198"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - service1
    networks:
      - mynetwork

  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "5001"
    depends_on:
      - service2
    deploy:
      replicas: 3 # Scale Service1 to 3 instances
    networks:
      - mynetwork

  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    expose:
      - "5002"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
