version: '3'
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - service2
  
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    expose:
      - "5002"
